#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c='clear'
alias ch='history -c && > ~/.bash_history'
# Default to human readable figures
alias df='df -h'
alias du='du -h'
alias e='$EDITOR'
alias gpush='git add . && git commit -m "minor updates" && git push'

alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour

alias map='xargs -n1'
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q='exit'

# Some shortcuts for different directory listings
# Not working on MacOS
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
# alias ls='command ls -hF --color=tty'                 # classify files in colour
# alias dir='ls --color --format=vertical'
# alias vdir='ls --color --format=long'
# alias lsd="l | grep --color=never '^d'"       # List only directories
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
alias tunnel='ssh -D 8080 -f -C -q -N '
alias spring-boot-maven='spring init spring-boot-maven --dependencies=web -build=maven; cd spring-boot-maven'
alias demo='open http://localhost:8080'
