#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e=$EDITOR
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias map='xargs -n1'
alias n='npm'
alias q='exit'
alias gpush='git add . && git commit -m "minor updates" && git push'
alias ginit='git add . && git commit -m "initial commit" && git push'
alias gclone='git clone' 

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

source "$DOTFILES_DIR_PATH/shell/os_x/aliases"
# if [ "$OS" == 'osx' ]; then
#     source "$DOTFILES_DIR_PATH/shell/os_x/aliases"
# elif [ "$OS" == 'ubuntu' ]; then
#     source "$DOTFILES_DIR_PATH/shell/ubuntu/aliases"
# fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
