#!/bin/bash

# Shell Variables
# http://linux.die.net/man/1/bash

# Make vim the default editor
export EDITOR='nano'

# History Options

# Ignore commands that start with spaces and duplicates
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines of history
# persisted in the Bash history file (default value is 500)
export HISTFILESIZE=10000

# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
export HISTIGNORE='&:[bf]g:c:clear:history:ls:exit:q:pwd:* --help'

# Increase the maximum number of commands recorded in the
# command history (default value is 500)
export HISTSIZE=10000

# Prefer US English and use UTF-8 encoding
export LANG='en_US'
export LC_ALL='en_US.UTF-8'

# Don't clear the screen after quitting a `man` page.
export MANPAGER="less -X"

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000)
# https://github.com/nodejs/node/blob/a85f4b5ce5791caf8caa9b31970313c6183a5499/doc/api/repl.markdown#persistent-history
export NODE_REPL_HISTORY_SIZE=10000

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr
export PYTHONIOENCODING='UTF-8'

export GOPATH=$HOME/go
export PATH=$HOME/bin:$GOROOT/bin:$GOPATH/bin/:$HOME/.cargo/bin:$PATH: