#!/bin/bash

# Readline library configuration options
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Try to stay at the same cursor position when moving through the history.
set history-preserve-point on

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Auto list TAB completions
# set show-all-if-ambiguous off
# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show all autocomplete results at once
set page-completions off

# If there are more than 100 possible completions for a word, ask to show them all
set completion-query-items 100

# Show extra file information when completing, like `ls -F` does
set visible-stats on

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
set skip-completed-text on

# Line editing
# -----------------------------------------------------------------------------
# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Miscellaneous
# -----------------------------------------------------------------------------
# Neither sound a beep nor flash the screen when trying to ring the bell.
set bell-style none
