#!/bin/sh

# Clear DNS cache
alias clear-dns-cache='sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder'

# Empty the trash, the main HDD and on all mounted volumes
# and clear Apple’s system logs to improve shell startup speed
alias empty-trash='sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* "delete from LSQuarantineEvent"'

# Hide/Show desktop icons
alias hide-desktop-icons='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias show-desktop-icons='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'

# Hide/Show hidden files in Finder
alias hide-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias show-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

# Lock screen
alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# Update
alias u='sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup \
            && npm install -g npm \
            && npm update -g'

# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

function screenshot.setjpg() {
    defaults write com.apple.screencapture type jpg
    killall SystemUIServer
}

function screenshot.setpng() {
    defaults write com.apple.screencapture type png
	killall SystemUIServer
}

# Java and Groovy
export JAVA_HOME=$(/usr/libexec/java_home)
export GRADLE_USER_HOME=/opt/gradle/gradle
export GRADLE_OPTS=-Dgradle.user.home=/Users/sergiu/dev/gradle
# Opt-out of Homebrew's analytics.
# https://github.com/Homebrew/brew/blob/0c95c60511cc4d85d28f66b58d51d85f8186d941/share/doc/homebrew/Analytics.md#opting-out
HOMEBREW_NO_ANALYTICS=1

# GO
export PATH=/usr/local/opt/go/libexec/bin:$PATH:
