#!/bin/sh

for file in ~/.{exports.local,exports,aliases,functions}; do
  [ -r "$file" ] && . "$file"
done
unset file

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear DNS cache

alias clear-dns-cache='sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty the trash, the main HDD and on all mounted volumes
# and clear Apple’s system logs to improve shell startup speed

alias empty-trash='sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* "delete from LSQuarantineEvent"'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons

alias hide-desktop-icons='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias show-desktop-icons='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show hidden files in Finder

alias hide-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias show-hidden-files='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen

alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update

alias u='sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup \
            && npm install -g npm \
            && npm update -g'

# Java and Groovy
export JAVA_HOME=$(/usr/libexec/java_home)

# Opt-out of Homebrew's analytics.
# https://github.com/Homebrew/brew/blob/0c95c60511cc4d85d28f66b58d51d85f8186d941/share/doc/homebrew/Analytics.md#opting-out
HOMEBREW_NO_ANALYTICS=1

# GO
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Binaries
export PATH=/usr/local/sbin:$PATH:$HOME/bin

source /usr/local/opt/chruby/share/chruby/chruby.sh
