#!/bin/sh

# Get local IP
alias local-ip="ifconfig | \
                | grep 'inet addr' \
                | grep -v '127.0.0.1' \
                | cut -d: -f2 \
                | cut -d' ' -f1"

# Empty Trash
alias empty-trash='rm -rf ~/.local/share/Trash/files/*'

# Update
alias u='sudo apt-get update \
            && sudo apt-get upgrade'

# Java and Groovy
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0
export GOROOT=/usr/lib/golang/

